name: itksnap

env:
  APPLICATION: itksnap
  PYTHON_VER: 3.8

on:
  push:
    paths:
      - recipes/*
      - recipes/itksnap/*
      - .github/workflows/itksnap.yml
      - .github/workflows/build.sh

  pull_request:
    paths:
      - recipes/*
      - recipes/itksnap/*
      - .github/workflows/itksnap.yml
      - .github/workflows/build.sh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Create recipe and build image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
          bash .github/workflows/build.sh
