name: Recipe Builder

on:
  push:
    paths:
      - recipes/itksnap/*
      - .github/workflows/recipe-builder.yml
  pull_request:
    paths:
      - recipes/itksnap/*
      - .github/workflows/recipe-builder.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run build.sh
        run: cd recipes/itksnap && cat build.sh && bash build.sh
      - name: Commit Dockerfile(s) back to repo
        run: |
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          git add .
          git commit -m "Update Repository"
          git push github HEAD:${GITHUB_REF}
