name: Recipe Builder

on:
  push:
    paths:
      - recipes/itksnap/*
      - .github/workflows/recipe-builder.yml
      - .github/workflows/build.sh
  pull_request:
    paths:
      - recipes/itksnap/*
      - .github/workflows/recipe-builder.yml
      - .github/workflows/build.sh

env:
  APPLICATION: itksnap

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Create recipe and build image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
          bash .github/workflows/build.sh
