name: template

on:
  push:
    paths:
      - recipes/*
      - recipes/template/*
      - .github/workflows/template.yml
      - .github/workflows/*.sh
 
  pull_request:
    paths:
      - recipes/*
      - recipes/template/*
      - .github/workflows/template.yml
      - .github/workflows/*.sh

env:
  DOCKERHUB_ORG: ${{ secrets.DOCKERHUB_ORG }}
  OS_PASSWORD: ${{ secrets.SWIFT_OS_PASSWORD }}
  OS_PROJECT_ID: ${{ secrets.SWIFT_OS_PROJECT_ID }}
  OS_USERNAME: ${{ secrets.SWIFT_OS_USERNAME }}
  OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_ID }}
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.SWIFT_OS_APPLICATION_CREDENTIAL_SECRET }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    outputs:
      BUILDDATE: ${{ steps.ENVVARS.outputs.BUILDDATE }}
      IMAGELIST: ${{ steps.IMAGEVARS.outputs.IMAGELIST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        id: ENVVARS
        run: |
          APPLICATION=$(basename $GITHUB_WORKFLOW .yml)
          SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)
          BUILDDATE=`date +%Y%m%d`
          echo "APPLICATION=$APPLICATION" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "BUILDDATE=$BUILDDATE" >> $GITHUB_ENV
          echo "::set-output name=BUILDDATE::$BUILDDATE"
  
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name : Build recipes
        run: |
          echo "APPLICATION: $APPLICATION"
          cd recipes/$APPLICATION
          /bin/bash build.sh

      - name: Set image variables
        id: IMAGEVARS
        run: |
          IMAGELIST=()
          for DOCKERFILE in recipes/$APPLICATION/*.Dockerfile; do
            IMAGENAME=$(echo $(basename $DOCKERFILE .Dockerfile) | tr '[A-Z]' '[a-z]')
            echo "IMAGENAME: $IMAGENAME"
            IMAGELIST+=$IMAGENAME
          done
          echo "IMAGELIST=$IMAGELIST" >> $GITHUB_ENV
          echo "::set-output name=IMAGELIST::$IMAGELIST"
      - name: Log into Github Package registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: Log into Dockerhub (optional)
        if: env.DOCKERHUB_ORG != ''
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Testing space
        run: |
            df -m /
            sudo apt-get remove -yqq aria2
            df -m /
            sudo apt-get remove -yqq ansible
            df -m /
            sudo apt-get remove -yqq azure-cli
            df -m /
            sudo apt-get remove -yqq shellcheck
            df -m /
            sudo apt-get remove -yqq rpm
            df -m /
            sudo apt-get remove -yqq xorriso
            df -m /
            sudo apt-get remove -yqq zsync
            df -m /
            sudo apt-get remove -yqq clang-6.0
            df -m /
            sudo apt-get remove -yqq lld-6.0
            df -m /
            sudo apt-get remove -yqq clang-format-6.0
            df -m /
            sudo apt-get remove -yqq clang-8
            df -m /
            sudo apt-get remove -yqq lld-8
            df -m /
            sudo apt-get remove -yqq clang-format-8
            df -m /
            sudo apt-get remove -yqq clang-9
            df -m /
            sudo apt-get remove -yqq lldb-9
            df -m /
            sudo apt-get remove -yqq lld-9
            df -m /
            sudo apt-get remove -yqq clangd-9
            df -m /
            sudo apt-get remove -yqq clang-format-9
            df -m /
            sudo apt-get remove -yqq dotnet-sdk-3.0
            df -m /
            sudo apt-get remove -yqq dotnet-sdk-3.1=3.1.101-1
            df -m /
            sudo apt-get remove -yqq esl-erlang
            df -m /
            sudo apt-get remove -yqq firefox
            df -m /
            sudo apt-get remove -yqq g++-8
            df -m /
            sudo apt-get remove -yqq g++-9
            df -m /
            sudo apt-get remove -yqq gfortran-8
            df -m /
            sudo apt-get remove -yqq gfortran-9
            df -m /
            sudo apt-get remove -yqq google-chrome-stable
            df -m /
            sudo apt-get remove -yqq google-cloud-sdk
            df -m /
            sudo apt-get remove -yqq ghc-8.8.3
            df -m /
            sudo apt-get remove -yqq ghc-8.10.1
            df -m /
            sudo apt-get remove -yqq cabal-install-3.2
            df -m /
            sudo apt-get remove -yqq heroku
            df -m /
            sudo apt-get remove -yqq imagemagick
            df -m /
            sudo apt-get remove -yqq libmagickcore-dev
            df -m /
            sudo apt-get remove -yqq libmagickwand-dev
            df -m /
            sudo apt-get remove -yqq libmagic-dev
            df -m /
            sudo apt-get remove -yqq ant
            df -m /
            sudo apt-get remove -yqq ant-optional
            df -m /
            sudo apt-get remove -yqq kubectl
            df -m /
            sudo apt-get remove -yqq mercurial
            df -m /
            sudo apt-get remove -yqq apt-transport-mttps
            df -m /
            sudo apt-get remove -yqq mono-complete
            df -m /
            sudo apt-get remove -yqq libmysqlclient-dev
            df -m /
            sudo apt-get remove -yqq mysql-server
            df -m /
            sudo apt-get remove -yqq mssql-tools
            df -m /
            sudo apt-get remove -yqq unixodbc-dev
            df -m /
            sudo apt-get remove -yqq yarn
            df -m /
            sudo apt-get remove -yqq bazel
            df -m /
            sudo apt-get remove -yqq chrpath
            df -m /
            sudo apt-get remove -yqq libssl-dev
            df -m /
            sudo apt-get remove -yqq libxft-dev
            df -m /
            sudo apt-get remove -yqq libfreetype6
            df -m /
            sudo apt-get remove -yqq libfreetype6-dev
            df -m /
            sudo apt-get remove -yqq libfontconfig1
            df -m /
            sudo apt-get remove -yqq libfontconfig1-dev
            df -m /
            sudo apt-get remove -yqq php7.1
            df -m /
            sudo apt-get remove -yqq php7.1-bcmath
            df -m /
            sudo apt-get remove -yqq php7.1-bz2
            df -m /
            sudo apt-get remove -yqq php7.1-cgi
            df -m /
            sudo apt-get remove -yqq php7.1-cli
            df -m /
            sudo apt-get remove -yqq php7.1-common
            df -m /
            sudo apt-get remove -yqq php7.1-curl
            df -m /
            sudo apt-get remove -yqq php7.1-dba
            df -m /
            sudo apt-get remove -yqq php7.1-enchant
            df -m /
            sudo apt-get remove -yqq php7.1-fpm
            df -m /
            sudo apt-get remove -yqq php7.1-gd
            df -m /
            sudo apt-get remove -yqq php7.1-gmp
            df -m /
            sudo apt-get remove -yqq php7.1-imap
            df -m /
            sudo apt-get remove -yqq php7.1-interbase
            df -m /
            sudo apt-get remove -yqq php7.1-intl
            df -m /
            sudo apt-get remove -yqq php7.1-json
            df -m /
            sudo apt-get remove -yqq php7.1-ldap
            df -m /
            sudo apt-get remove -yqq php7.1-mbstring
            df -m /
            sudo apt-get remove -yqq php7.1-mcrypt
            df -m /
            sudo apt-get remove -yqq php7.1-mysql
            df -m /
            sudo apt-get remove -yqq php7.1-odbc
            df -m /
            sudo apt-get remove -yqq php7.1-opcache
            df -m /
            sudo apt-get remove -yqq php7.1-pgsql
            df -m /
            sudo apt-get remove -yqq php7.1-phpdbg
            df -m /
            sudo apt-get remove -yqq php7.1-pspell
            df -m /
            sudo apt-get remove -yqq php7.1-readline
            df -m /
            sudo apt-get remove -yqq php7.1-recode
            df -m /
            sudo apt-get remove -yqq php7.1-snmp
            df -m /
            sudo apt-get remove -yqq php7.1-soap
            df -m /
            sudo apt-get remove -yqq php7.1-sqlite3
            df -m /
            sudo apt-get remove -yqq php7.1-sybase
            df -m /
            sudo apt-get remove -yqq php7.1-tidy
            df -m /
            sudo apt-get remove -yqq php7.1-xml
            df -m /
            sudo apt-get remove -yqq php7.1-xmlrpc
            df -m /
            sudo apt-get remove -yqq php7.1-xsl
            df -m /
            sudo apt-get remove -yqq php7.1-zip
            df -m /
            sudo apt-get remove -yqq php7.2
            df -m /
            sudo apt-get remove -yqq php7.2-bcmath
            df -m /
            sudo apt-get remove -yqq php7.2-bz2
            df -m /
            sudo apt-get remove -yqq php7.2-cgi
            df -m /
            sudo apt-get remove -yqq php7.2-cli
            df -m /
            sudo apt-get remove -yqq php7.2-common
            df -m /
            sudo apt-get remove -yqq php7.2-curl
            df -m /
            sudo apt-get remove -yqq php7.2-dba
            df -m /
            sudo apt-get remove -yqq php7.2-enchant
            df -m /
            sudo apt-get remove -yqq php7.2-fpm
            df -m /
            sudo apt-get remove -yqq php7.2-gd
            df -m /
            sudo apt-get remove -yqq php7.2-gmp
            df -m /
            sudo apt-get remove -yqq php7.2-imap
            df -m /
            sudo apt-get remove -yqq php7.2-interbase
            df -m /
            sudo apt-get remove -yqq php7.2-intl
            df -m /
            sudo apt-get remove -yqq php7.2-json
            df -m /
            sudo apt-get remove -yqq php7.2-ldap
            df -m /
            sudo apt-get remove -yqq php7.2-mbstring
            df -m /
            sudo apt-get remove -yqq php7.2-mysql
            df -m /
            sudo apt-get remove -yqq php7.2-odbc
            df -m /
            sudo apt-get remove -yqq php7.2-opcache
            df -m /
            sudo apt-get remove -yqq php7.2-pgsql
            df -m /
            sudo apt-get remove -yqq php7.2-phpdbg
            df -m /
            sudo apt-get remove -yqq php7.2-pspell
            df -m /
            sudo apt-get remove -yqq php7.2-readline
            df -m /
            sudo apt-get remove -yqq php7.2-recode
            df -m /
            sudo apt-get remove -yqq php7.2-snmp
            df -m /
            sudo apt-get remove -yqq php7.2-soap
            df -m /
            sudo apt-get remove -yqq php7.2-sqlite3
            df -m /
            sudo apt-get remove -yqq php7.2-sybase
            df -m /
            sudo apt-get remove -yqq php7.2-tidy
            df -m /
            sudo apt-get remove -yqq php7.2-xml
            df -m /
            sudo apt-get remove -yqq php7.2-xmlrpc
            df -m /
            sudo apt-get remove -yqq php7.2-xsl
            df -m /
            sudo apt-get remove -yqq php7.2-zip
            df -m /
            sudo apt-get remove -yqq php7.3
            df -m /
            sudo apt-get remove -yqq php7.3-bcmath
            df -m /
            sudo apt-get remove -yqq php7.3-bz2
            df -m /
            sudo apt-get remove -yqq php7.3-cgi
            df -m /
            sudo apt-get remove -yqq php7.3-cli
            df -m /
            sudo apt-get remove -yqq php7.3-common
            df -m /
            sudo apt-get remove -yqq php7.3-curl
            df -m /
            sudo apt-get remove -yqq php7.3-dba
            df -m /
            sudo apt-get remove -yqq php7.3-dev
            df -m /
            sudo apt-get remove -yqq php7.3-enchant
            df -m /
            sudo apt-get remove -yqq php7.3-fpm
            df -m /
            sudo apt-get remove -yqq php7.3-gd
            df -m /
            sudo apt-get remove -yqq php7.3-gmp
            df -m /
            sudo apt-get remove -yqq php7.3-imap
            df -m /
            sudo apt-get remove -yqq php7.3-interbase
            df -m /
            sudo apt-get remove -yqq php7.3-intl
            df -m /
            sudo apt-get remove -yqq php7.3-json
            df -m /
            sudo apt-get remove -yqq php7.3-ldap
            df -m /
            sudo apt-get remove -yqq php7.3-mbstring
            df -m /
            sudo apt-get remove -yqq php7.3-mysql
            df -m /
            sudo apt-get remove -yqq php7.3-odbc
            df -m /
            sudo apt-get remove -yqq php7.3-opcache
            df -m /
            sudo apt-get remove -yqq php7.3-pgsql
            df -m /
            sudo apt-get remove -yqq php7.3-phpdbg
            df -m /
            sudo apt-get remove -yqq php7.3-pspell
            df -m /
            sudo apt-get remove -yqq php7.3-readline
            df -m /
            sudo apt-get remove -yqq php7.3-recode
            df -m /
            sudo apt-get remove -yqq php7.3-snmp
            df -m /
            sudo apt-get remove -yqq php7.3-soap
            df -m /
            sudo apt-get remove -yqq php7.3-sqlite3
            df -m /
            sudo apt-get remove -yqq php7.3-sybase
            df -m /
            sudo apt-get remove -yqq php7.3-tidy
            df -m /
            sudo apt-get remove -yqq php7.3-xml
            df -m /
            sudo apt-get remove -yqq php7.3-xmlrpc
            df -m /
            sudo apt-get remove -yqq php7.3-xsl
            df -m /
            sudo apt-get remove -yqq php7.3-zip
            df -m /
            sudo apt-get remove -yqq php7.4
            df -m /
            sudo apt-get remove -yqq php7.4-bcmath
            df -m /
            sudo apt-get remove -yqq php7.4-bz2
            df -m /
            sudo apt-get remove -yqq php7.4-cgi
            df -m /
            sudo apt-get remove -yqq php7.4-cli
            df -m /
            sudo apt-get remove -yqq php7.4-common
            df -m /
            sudo apt-get remove -yqq php7.4-curl
            df -m /
            sudo apt-get remove -yqq php7.4-dba
            df -m /
            sudo apt-get remove -yqq php7.4-dev
            df -m /
            sudo apt-get remove -yqq php7.4-enchant
            df -m /
            sudo apt-get remove -yqq php7.4-fpm
            df -m /
            sudo apt-get remove -yqq php7.4-gd
            df -m /
            sudo apt-get remove -yqq php7.4-gmp
            df -m /
            sudo apt-get remove -yqq php7.4-imap
            df -m /
            sudo apt-get remove -yqq php7.4-interbase
            df -m /
            sudo apt-get remove -yqq php7.4-intl
            df -m /
            sudo apt-get remove -yqq php7.4-json
            df -m /
            sudo apt-get remove -yqq php7.4-ldap
            df -m /
            sudo apt-get remove -yqq php7.4-mbstring
            df -m /
            sudo apt-get remove -yqq php7.4-mysql
            df -m /
            sudo apt-get remove -yqq php7.4-odbc
            df -m /
            sudo apt-get remove -yqq php7.4-opcache
            df -m /
            sudo apt-get remove -yqq php7.4-pgsql
            df -m /
            sudo apt-get remove -yqq php7.4-phpdbg
            df -m /
            sudo apt-get remove -yqq php7.4-pspell
            df -m /
            sudo apt-get remove -yqq php7.4-readline
            df -m /
            sudo apt-get remove -yqq php7.4-snmp
            df -m /
            sudo apt-get remove -yqq php7.4-soap
            df -m /
            sudo apt-get remove -yqq php7.4-sqlite3
            df -m /
            sudo apt-get remove -yqq php7.4-sybase
            df -m /
            sudo apt-get remove -yqq php7.4-tidy
            df -m /
            sudo apt-get remove -yqq php7.4-xml
            df -m /
            sudo apt-get remove -yqq php7.4-xmlrpc
            df -m /
            sudo apt-get remove -yqq php7.4-xsl
            df -m /
            sudo apt-get remove -yqq php7.4-zip
            df -m /
            sudo apt-get remove -yqq php-amqp
            df -m /
            sudo apt-get remove -yqq php-apcu
            df -m /
            sudo apt-get remove -yqq php-igbinary
            df -m /
            sudo apt-get remove -yqq php-memcache
            df -m /
            sudo apt-get remove -yqq php-memcached
            df -m /
            sudo apt-get remove -yqq php-mongodb
            df -m /
            sudo apt-get remove -yqq php-redis
            df -m /
            sudo apt-get remove -yqq php-xdebug
            df -m /
            sudo apt-get remove -yqq php-zmq
            df -m /
            sudo apt-get remove -yqq snmp
            df -m /
            sudo apt-get remove -yqq pollinate
            df -m /
            sudo apt-get remove -yqq libpq-dev
            df -m /
            sudo apt-get remove -yqq postgresql-client
            df -m /
            sudo apt-get remove -yqq powershell
            df -m /
            sudo apt-get remove -yqq ruby-full
            df -m /
            sudo apt-get remove -yqq sphinxsearch
            df -m /
            sudo apt-get remove -yqq subversion
            df -m /
            sudo apt-get remove -yqq mongodb-org
            df -m /

#       - name: Free up disk space on runner (optional)
#         if: env.APPLICATION == 'fsl' || env.APPLICATION == 'mrtrix3'
#         run: bash .github/workflows/free-up-space.sh
#       - name : Run docker builder + Upload to docker and github registry
#         run: for IMAGENAME in "${IMAGELIST[@]}"; do /bin/bash .github/workflows/build-docker.sh $IMAGENAME; done

#   build-singularity:
#     runs-on: ubuntu-latest
#     needs: build-docker
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set environment variables
#         run: |
#           APPLICATION=$(basename $GITHUB_WORKFLOW .yml)
#           BUILDDATE=${{needs.build-docker.outputs.BUILDDATE}}
#           echo "APPLICATION=$APPLICATION" >> $GITHUB_ENV
#           echo "BUILDDATE=$BUILDDATE" >> $GITHUB_ENV
#       - name: Log into Github Package registry
#         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
#       - name: Log into Dockerhub (optional)
#         if: env.DOCKERHUB_ORG != ''
#         run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#       - name: Free up disk space on runner (optional)
#         if: env.APPLICATION == 'fsl' || env.APPLICATION == 'mrtrix3'
#         run: bash .github/workflows/free-up-space.sh
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - name : Run singularity builder + Upload singularity registry
#         run: | 
#           IMAGELIST=${{needs.build-docker.outputs.IMAGELIST}}
#           for IMAGENAME in "${IMAGELIST[@]}"; do /bin/bash .github/workflows/build-singularity.sh $IMAGENAME; done
